### ISSUE TITLE
Project timeline?

### ISSUE THREAD

**Issue by quinton-ashley** [Birch-san/box2d3-wasm#2]
Hi! It's awesome to see that you're working on porting Box2D v3. I'd like to help with this effort! 😃

I was able to build `Box2D.simd.wasm` and run the `hello World {}` (funny) integration test.

I see an initial PR for shape bindings. I have no experience with emscripten, so forgive my ignorance, but will it be fairly straightforward to complete the project at this point just by adding more bindings, or are their other hurdles? Do you want help from contributors?

I know you just recently published this repo 5 days ago, but if you could give a timeline on when the project will be complete, I'd really appreciate it!

**Comment by Birch-san** [comment]
no timelines. just doing this in scraps of time on occasional weekends.

maybe bindings is all we need (and @ErikSoem has contributed a lot of coverage already https://github.com/Birch-san/box2d3-wasm/pull/1).  
but Box2D v3 adds threading and SIMD.  

SIMD support _might_ be free and already working (it's compiling with SIMD enabled, just don't know whether it's compiling it to WASM SIMD instructions or downlevelling to slower non-SIMD instructions).

Threading support… I have no idea whether that's working (the only thing I've done is construct an instance of b2World), and the security model of web browsers means that how you compile, bundle and deploy threaded code could be much harder than in native code.  
I'm using the pthread support from https://github.com/erincatto/box2d/pull/841, and compilation succeeded but I don't know whether the functionality works (and whether it has actual concurrency via web workers or fake support like asynchronicity via microtasks); need to get more bindings and make an example to exercise them.

Bindings isn't just a problem of copy-pasting; there are more complex types for which we'll need to figure out C++ gymnastics to bind to. Callbacks are hard.

But if that stuff goes smoothly, it'll still take some time to build demos/documentation that try out all the functionality.

Building the library and throwing it untested on npm is easier than building demos and docs for it. But then people will just ask me how to use it and my answer will be I don't know.

**Comment by StepanMynarik** [comment]
@Birch-san Pardon me for my ignorance, no experience with this stuff. But shouldn't it be possible to just use WebIDL bindings instead of C++ glue layer?

Just asking because it would be simpler for me to maintain in years to come and to just wrap my head around.

**Comment by Birch-san** [comment]
I used WebIDL for the previous version, but my conclusion is it's not very good. embind is way better.

for original [box2d-wasm](https://github.com/Birch-san/box2d-wasm), WebIDL made sense because kripken had already provided a lot of [WebIDL bindings](https://github.com/kripken/box2d.js/blob/master/Box2D_v2.3.1.idl) for [box2d.js](https://github.com/kripken/box2d.js/).

but the WebIDL binder didn't provide typescript types, which forced me to write my own compiler. this required parsing WebIDL, which required me to write hacks over an existing parser (Emscripten's WebIDL isn't the same WebIDL that is used elsewhere, so the WebIDL parser I found was not compatible).

there's a bunch of things that WebIDL can't bind to (check the ~40 comments I left in the .idl file, and note that for liquidfun it's probably worse):  
https://github.com/Birch-san/box2d-wasm/blob/c2d7e244787bfc619c1ea80d09e7ceb72294be85/box2d-wasm/Box2D.idl#L967  
the stupidest of which is that it can only bind to classes/methods, not functions. this gets a lot worse in box2d v3, which ditches C++ to lean more heavily into C.

glue_stub.cpp is basically a story of "everything I wasn't able to bind to with WebIDL and had to write manually instead":  
https://github.com/Birch-san/box2d-wasm/blob/master/box2d-wasm/glue_stub.cpp

the strategy this time is to rely on [box2cpp](https://github.com/HolyBlackCat/box2cpp) for an object-oriented C++-style interface. those bindings are generated automatically via awk, and seem robust enough that they've survived a few version updates so far. then we use embind to bind to the box2cpp bindings. this isn't ideal but it's not too painful either; box2d v3 is stabilising, we've got decent coverage of its APIs and I assume it's not gonna change too drastically from here. 

writing embind is very similar effort to writing WebIDL, moreover it's _all_ you need to do. the compiler tells you if it's right, and there's no other steps like having to build your own compiler for type declarations; they give you the TypeScript for free. and embind can actually bind to moreorless everything. we occasionally have to break out into lambdas for more complicated stuff, but in WebIDL there wasn't a way to do "more complicated stuff" at all.
